### PR TITLE
#105 Add Doctrine psalm plugin

### PR DESCRIPTION
**Pull request by githoober**
Fulfills #105

### CODE REVIEW

**Comment by jakzal** [comment]
Thank you @githoober 🍺

**Comment by dkarlovi** [comment]
How do you actually use this within the Docker image? There doesn't seem to be a `psalm-plugin` available in the path.

**Comment by dkarlovi** [comment]
Never mind, I need to run a different copy of Psalm, the one in 

```
/tools/.composer/vendor-bin/doctrine-psalm-plugin/vendor/bin/psalm
```

The namespace hints you cannot have two plugins installed at the same time? We might want to move it to `psalm` namespace or something.

**Comment by jakzal** [comment]
Looking at now I’m not sure why it’s in its own namespace.

**Comment by dkarlovi** [comment]
I'm fine with each tool being in its own namespace since they're stand-alone from each other, but the plugins should then be in that tool's namespace, not each plugin in its own. The idea here should definitely be the base `psalm` tool should have access to its plugins.

**Comment by jakzal** [comment]
@dkarlovi fancy to create a PR?

**Comment by dkarlovi** [comment]
@jakzal  Yes, I'll add Psalm's Symfony and PHPUnit plugins this week so let's fix it all together, if you agree.

**Pull request merged**
