### PR TITLE
Add PHP Architecture Tester

### PR DESCRIPTION
**Pull request by carlosas**
PHP Architecture Tester is a static analysis tool to verify architectural requirements.
It provides a natural language abstraction to define your own architectural rules and test them against your software.

There are four groups of supported assertions: Dependency, Inheritance, Composition and Mixin.

### CODE REVIEW

**Comment by carlosas** [comment]
PHPAT does not have a `-v` option or any other dummy command. How can I make your CI pass without that run?

**Comment by jakzal** [comment]
The `test` section doesn't necessarily need to use `-v`. It's purpose is to quickly verify if tool was installed. Displaying the version, listing available command or any similar "lightweight" invocation will work.

**Comment by carlosas** [comment]
Well, the tool does not have such thing 😅
Is it a mandatory field?

**Comment by jakzal** [comment]
Not even a "help" command? That's a first tool like that.

I'd have to double check, but i think the "test" section is required. If we can't run the command to make sure it actually runs, we'll have to do with sth simpler, like verifying a file exists.

**Pull request merged**
