### PR TITLE
Add Laravel Pint CS tool

### PR DESCRIPTION
**Pull request by benjy8001**

### CODE REVIEW

**Comment by benjy8001** [comment]
@jakzal , i have this error on your pipeline : 
`Error:    Could not resolve requested PHAR humbug/box`

Any idea ?

**Comment by jakzal** [comment]
@benjy8001 it's not your fault. Something's got broken on box' side. Master builds are failing too.

**Comment by jakzal** [comment]
@benjy8001 actually, did you rebase your branch? Seems that everything is fine on the master branch now.

**Comment by benjy8001** [comment]
Ok, i will try this week-end. But when i open this PR it was the case.

**Comment by benjy8001** [comment]
@jakzal , same issue ... And i'm on top of master (last commit id 1bfba349f983414d21d7e3bbcbdaa920be903744)

**Comment by jakzal** [comment]
@benjy8001 can you send a completely new PR containing this change? If you're still interested that is. I don't know what was going on here.

**Pull request closed without merging**
