### PR TITLE
Use the prefixed phar version of easy coding standard

### LINKED ISSUE #220: Scoping the tools
I wanted to contribute scoping of one of the tools that toolbox ships because there are scoping issues when running it in one of our projects. To do this, I expected some tools would already be scoped so I can get inspiration what modifications in tools.json file I need to make. But looking into this json file, I don't see any such configuration in existing tools. Does this mean toolbox currently does not do scoping of any of the current tools whatsoever?

Ref https://github.com/symplify/symplify/issues/1872

### PR DESCRIPTION
**Pull request by jakzal**
Fixes #220

### CODE REVIEW

**Comment by ostrolucky** [comment]
> Before merging I'd love you to test it if possible.

Sorry but I don't currently know how would I go around reviewing and testing this. How do I install just one tool via toolbox?

**Comment by jakzal** [comment]
Good point. I don't think there's a way to install a single tool currently...

For the purpose of testing `ecs`, I think it's enough if you installed `symplify/easy-coding-standard-prefixed` with composer and confirm it does not prefix sniffs etc.

**Comment by ostrolucky** [comment]
I do confirm that

**Comment by jakzal** [comment]
Thanks!

**Pull request merged**
