### PR TITLE
bump: Infection ^0.26

### PR DESCRIPTION
**Pull request by dkarlovi**

### CODE REVIEW

**Comment by dkarlovi** [comment]
Failure related to GH rate limits. :thinking:

**Comment by jakzal** [comment]
Thanks @dkarlovi 🍺

**Comment by jakzal** [comment]
@dkarlovi I suspect that my github token isn't used when tests are run from fork branches and that's why we hit GH rate limits 🤔

**Comment by jakzal** [comment]
aaand now I know why infection was locked to an old version. The latest doesn't support PHP 7.4.

**Pull request merged**
