### PR TITLE
feat: added phpstan/extension-installer in the list of PHPStan packages

### PR DESCRIPTION
**Pull request by dgoosens**
hi @jakzal 

as requested in #421 , I've added the `phpstan/extension-installer` package to list of items that is to be installed in the toolbox

dGo

### CODE REVIEW

**Comment by dgoosens** [comment]
hi @jakzal 

Looks like something is wrong with the integration tests...  

```
Could not resolve requested PHAR humbug/box
```

Don't think that has anything to do with the code itself...

dGo

**Comment by jakzal** [comment]
Looks like a problem on PRs only 🤔

**Comment by dgoosens** [comment]
is there something I can do about it ?

**Comment by jakzal** [comment]
It looks good. I'll merge it and hope it passes. It should as nightly builds have passed.

**Pull request merged**
