### PR TITLE
phpcs-security-audit > Add Security ruleset to phpcs

### PR DESCRIPTION
**Pull request by mihai-stancu**
Hello,

I'd like to propose the addition of a `phpcs` security ruleset provided by FloeDesignTechnologies [here](https://github.com/FloeDesignTechnologies/phpcs-security-audit).

### Approach

Since it's a `phpcs` ruleset it's not a standalone command so it cannot be installed via `phar-download` or `composer-bin-plugin` so I used `composer-global-install` which incidentally also installs `squizlabs/PHP_CodeSniffer` as a dependency.

### Drawbacks

The package also requires `dealerdirect/phpcodesniffer-composer-installer` which normally would configure `phpcs` to recognize the new ruleset but since it does that by discovering where `phpcs` is installed via composer it will not discover the correct `phpcs` binary (from `/tools`). So I also executed a `sh` line to correcly configure `phpcs`.

There seem to be a lot of drawbacks to this approach. The only alternative I see would be downloading rulesets separately. Please advise.

### CODE REVIEW

**Comment by jakzal** [comment]
> Since it's a phpcs ruleset it's not a standalone command so it cannot be installed via phar-download or composer-bin-plugin so I used composer-global-install which incidentally also installs squizlabs/PHP_CodeSniffer as a dependency.

Why composer-bin-plugin cannot be used?

**Comment by mihai-stancu** [comment]
> > Since it's a phpcs ruleset it's not a standalone command so it cannot be installed via phar-download or composer-bin-plugin so I used composer-global-install which incidentally also installs squizlabs/PHP_CodeSniffer as a dependency.
> 
> Why composer-bin-plugin cannot be used?

Apologies, I didn't fully understand how `composer-bin-plugin` worked and made some wrong assumptions. It can be done via `composer-bin-plugin`, I'll update the PR.

I could also change `phpcs` from `phar-download` to `composer-bin-plugin` so that:
- they share the same namespace
- `phpcs` only gets installed once
- the `dealerdirect/phpcodesniffer-composer-installer` autodiscovery would work
- we would not need to use the `sh` configuration thing

**Comment by jakzal** [comment]
> I could also change phpcs from phar-download to composer-bin-plugin

Please, do that. Thanks!

**Comment by mihai-stancu** [comment]
Note: `phpcs` is actually already installed as a dependency of `phpinsights` but I think it's just using `phpcs`, not integrating with it.

Should the namespace I'm adding be `phpcs` because I'm adding `phpcs` + some rulesets?

**Comment by mihai-stancu** [comment]
I'm having a bit of trouble after running `composer global bin phpcs require pheromone/phpcs-security-audit` manually, it doesn't have `dealerdirect/phpcodesniffer-composer-install` inside the namespace although it's a dependency.

**Comment by mihai-stancu** [comment]
My bad, v2.0.1 doesn't actually require `dealerdirect/phpcodesniffer-composer-install` which is why it was never installed / triggered.

**Comment by jakzal** [comment]
Looks good. Ready?

**Comment by jakzal** [comment]
@mihai-stancu you might want to clean up your branch. Perhaps rebase?

Also, it seems that your commiter email address is not connected to your github account.

**Comment by mihai-stancu** [comment]
Hey,

I experimented a bit last night and was waiting for the Scrutinizer check to pass in the morning.

I'll rebase soon. 10ks.

**Comment by mihai-stancu** [comment]
The PR looks clean now after the rebase. All good?

**Review by jakzal — APPROVED** [review]

**Comment by jakzal** [comment]
@mihai-stancu can you do one more thing for me and run `bin/devkit.php update:readme` and commit changes please?

**Comment by mihai-stancu** [comment]
I've done that, but there's a catch -- by adding the phpcodesniffer-composer-install plugin explicitly as a tool in the `phpcs.json` file it gets automatically added to the `README`.

Is there a way to specify that it shouldn't?

**Comment by jakzal** [comment]
That's fine. Keep it simple.

**Comment by mihai-stancu** [comment]
So should we let the `phpcodesniffer-composer-install` line appear in the README (i.e.: should I rerun the devkit and update the README)?

**Comment by jakzal** [comment]
Yes, please. Let's not make exceptions. We already list other "pre-installation" type of tools.

**Comment by jakzal** [comment]
Thank you @mihai-stancu 🍺

**Pull request merged**
