### PR TITLE
Remove PHP_Testability, DesignPatternDetector

### LINKED ISSUE #117: Abandoned packages used
```
Package halleck45/phpmetrics is abandoned, you should avoid using it.
Use phpmetrics/phpmetrics instead.

Package edsonmedina/php_testability is abandoned, you should avoid using it.
No replacement was suggested.
```

Spotted in the build :angel:

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #117

For `halleck45/phpmetrics`, it's part of https://github.com/Halleck45/DesignPatternDetector 

Last commit 4 years ago, i'm not sure i should open a PR there :sweat_smile: do we want to keep it?

### CODE REVIEW

**Comment by jakzal** [comment]
Can you move it in the README to a new list below the current one? Header can be called something like "Abandoned tools".

Let's remove the other one too. They're not really usable.

**Comment by ro0NL** [comment]
You mean somewhat like a reference changelog of tools once available,  but removed meanwhile? Do we want to keep track of that actually.. i.e. why not a release changelog instead?

**Comment by jakzal** [comment]
Yeah, i just want to keep removed tools on the list, so they could still be found. Some people use this list as a resource of available tools .

**Comment by jakzal** [comment]
Cheers 🍺

**Pull request merged**
