### PR TITLE
Bump paratest to v6.2.0 and enable on php 8

### PR DESCRIPTION
**Pull request by Pen-y-Fan**
Linked to plan #357

### CODE REVIEW

**Comment by Pen-y-Fan** [comment]
From v6.0 there is no phar file 🙁

**Comment by jakzal** [comment]
https://github.com/paratestphp/paratest/issues/598

**Comment by jakzal** [comment]
Looks like this needs to be migrated to composer-bin-plugin.

**Comment by jakzal** [comment]
Thank you @Pen-y-Fan 🍺

**Pull request merged**
