### PR TITLE
Add composer unused tool

### PR DESCRIPTION
**Pull request by benjy8001**
Adding Composer tool to show unused Composer dependencies by scanning your code.

### CODE REVIEW

**Comment by jakzal** [comment]
This is great. Can you run `bin/devkit.php update:readme` and commit the updated readme please?

**Comment by jakzal** [comment]
Just noticed they recommend installing the phar: https://github.com/composer-unused/composer-unused#phar-php-archive-recommended

We should favour phars over other installation methods. Can you switch the installation method to phar as well please?

**Comment by benjy8001** [comment]
Thanks.

I just push the update.

**Comment by jakzal** [comment]
Thank you 🍺

**Pull request merged**
