### PR TITLE
feat: PHP 8.3

### PR DESCRIPTION
**Pull request by dkarlovi**

### CODE REVIEW

**Comment by jakzal** [comment]
Ugh... this one's going to be a bit more involved.

I think I might need to rip out prophecy and replace it with PHPUnit mocks.

**Comment by dkarlovi** [comment]
I got it partially working locally, but it needs to use yet unreleased packages, moving to PHPUnit mocks is probably for the best long term.

**Comment by dkarlovi** [comment]
I just got a notification on my phone saying (without context)

> Prophecy is gone. 

Seemed like Zeus was sending me a text. :rofl:

**Comment by dkarlovi** [comment]
build fails, did you mean to release 2.7.0 here?
https://github.com/jakzal/phpunit-globals/releases/tag/v3.2.0

**Comment by jakzal** [comment]
No. Let's drop PHP 8.0 here if it's causing problems.

**Comment by dkarlovi** [comment]
Makes sense, 8.0 is EOL.

**Comment by dkarlovi** [comment]
Replaced by #493

**Comment by jakzal** [comment]
@dkarlovi I had to create a new PR so that builds could use secrets.

**Comment by dkarlovi** [comment]
No problem! :beers:

**Pull request closed without merging**
