### PR TITLE
Add support for phive-install.

### PR DESCRIPTION
**Pull request by mihai-stancu**
Hi,

I'm trying to add [`phive`](https://phar.io/) as an installer here. It's prepackaged to do what `phar-download` does and I've seen various tool starting to recommend it as "the way" to install their tool.

WDYT?

### CODE REVIEW

**Comment by jakzal** [comment]
Great idea. It should be prefered over phar-download 👍

**Comment by jakzal** [comment]
To help with infection coverage you should add a test to the InstallToolsTest. Similar to the one for phar-download: https://github.com/jakzal/toolbox/blob/master/tests/UseCase/InstallToolsTest.php#L151-L160

**Comment by mihai-stancu** [comment]
Question: (as a matter of test philosophy) since you (fully) control the input, then why use regex to match the output, why not match against the exact expected command string?

**Comment by jakzal** [comment]
> Question: (as a matter of test philosophy) since you (fully) control the input, then why use regex to match the output, why not match against the exact expected command string?

If the test was checking for the exact output, it would be more coupled to the implementation. All I want to make sure here is that curl is called to download the phar. I don't care about specific options or the order. The actual command invocation is tested in the integrated test.

**Comment by mihai-stancu** [comment]
Alright, 10q for the clarification.

I'll pingback in a couple of days -- when I find the time to finish this.

**Comment by jakzal** [comment]
No rush! Thank you for working on this.

**Comment by mihai-stancu** [comment]
I'll close this one since the integration tests here aren't revealing faults in the implementation and we'll rely on #369 to finish the job.

**Pull request closed without merging**
