### PR TITLE
Add composer-require-checker

### PR DESCRIPTION
**Pull request by mihai-stancu**
Adds [composer-require-checker](https://github.com/maglnet/ComposerRequireChecker).

I removed the `phive` dependency because it looks like that will need a bit more work.

### CODE REVIEW

**Comment by mihai-stancu** [comment]
Checks pass here.

Removed the `phive` dependency.

**Comment by jakzal** [comment]
@mihai-stancu Can you run `bin/devkit.php update:readme` and commit changes?

**Comment by mihai-stancu** [comment]
Done!

**Comment by jakzal** [comment]
Thank you @mihai-stancu 🍺

**Comment by mihai-stancu** [comment]
Woop! Woop!

:beers:

**Pull request merged**
