### PR TITLE
add simple-phpunit wrapper tool

### LINKED ISSUE #32: Add Symfony PHPUnit bridge tool
what about adding `simple-phpunit`?

https://github.com/symfony/phpunit-bridge/tree/master/bin

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #32 

`php bin/toolbox.php install` :+1: 
`bin/toolbox.php list-tools` :+1: 
`php bin/toolbox.php test` :+1: 
`php bin/devkit.php update:readme` :+1:

### CODE REVIEW

**Comment by ro0NL** [comment]
note the test is preceded by an auto-install of the wrapped phpunit, causing a bit of extra output: https://travis-ci.com/jakzal/toolbox/jobs/169989651#L1303

not sure how to avoid it, then again it's needed for testing :sweat_smile:

**Comment by jakzal** [comment]
Hm... could we try sth like:

```
 "command": [
         "composer-bin-plugin": {
           "package": "symfony/phpunit-bridge",
           "namespace": "symfony"
         },
"sh": {
     "command": "simple-phpunit --version"
}
]
```

Not sure about exact syntax. I'd like to make sure all required files are installed on the image when we run this on docker.

**Comment by ro0NL** [comment]
the wrapped installation are not required files, those can vary depending on SYMFONY_PHPUNIT_VERSION env, as such multiple dists live in `vendor/bin/.phpunit/phpunit-X.Y`

it's a phpunit version manager basically :) so what about `test -f vendor/bin/simple-phpunit` for a test? and avoid invoking the binary (im not sure these files get included in the final dist at this point).

AFAIK there's no way to opt out from auto-installing. It's a wrapper, it's more or less required by design :) as such we should simply test the composer installation is OK.

**Comment by jakzal** [comment]
So how is it going to work on docker?

**Comment by ro0NL** [comment]
i've updated the test, it simply checks if the command exists:

```
/app # type simple-phpunit
simple-phpunit is /tools/.composer/vendor/bin/simple-phpunit
/app # echo $?
0
/app # type boo
boo: not found
/app # echo $?
127
```

let's see :)

**Comment by jakzal** [comment]
But what will happen once we install it on a docker image? Wouldn't each call trigger a phpunit installation?

**Comment by ro0NL** [comment]
Hi @jakzal, it depends ...

`simple-phpunit` will only install the wrapped phpunit on the first call, if it's not intalled yet. Possibly it can be done as an explicit step: `simple-phpunit install`. Once available it will forward everything to the wrapped `phpunit` binary.

If i understand well, we'll only lose it once the container/image gets destroyed/removed, triggering a re-install each time.

The wrapped binary can be installed in a custom location ([ref](https://github.com/symfony/phpunit-bridge/blob/master/bin/simple-phpunit#L75)), or by running a container with `-e COMPOSER_HOME=/path` or the proper volumes i suppose.

Currently i'm doing the same already by leveraging `composer global require` on the QA image.

**Comment by jakzal** [comment]
> Possibly it can be done as an explicit step: simple-phpunit install.

That's why I was asking if the following helped:

```
 "command": [
         "composer-bin-plugin": {
           "package": "symfony/phpunit-bridge",
           "namespace": "symfony"
         },
    "sh": {
         "command": "simple-phpunit --version"
    }
]
```

**Comment by jakzal** [comment]
Great job! I'll have a closer look asap.

**Pull request merged**
