### PR TITLE
Install phpcpd for PHP 7.2

### PR DESCRIPTION
**Pull request by benjy8001**
Link to #209

### CODE REVIEW

**Comment by jakzal** [comment]
Do you need it on PHP 7.2? 

Normally I'd rather drop support unless there's someone who really needs it.

**Comment by benjy8001** [comment]
> Do you need it on PHP 7.2?
> 
> Normally I'd rather drop support unless there's someone who really needs it.

Hi, actually i build my own image, based on php7.2.10-alpine, add the lastest toolbox release, so i added phpcdp on my Dockerfiles in order to keep it in my phpqa image.

If i use 7.3 base image, it could result on some deprecated code (or other), so, i think, while php7.2 is supported on phpqa, you must have the same tools on each images. Otherwise, maybe add in the Readme in which php version the tool is available.

**Comment by jakzal** [comment]
> Otherwise, maybe add in the Readme in which php version the tool is available.

This information is availble on the list generated on each build: https://jakzal.github.io/toolbox/
Could consider adding to the readme, but no sure if it's worth the effort.

I didn't feel obligated to provide all the tools on each version. To take phpcpd as an example, it was installed on the phpqa at some point in past, so people stuck on legacy PHP version can use the old image. 

Nevertheless, we do install multiple versions of some tools - like phpunit (which has a bit clearer release cycle). I'm on a fence here.

**Comment by jakzal** [comment]
@benjy8001 we're going to drop PHP 7.2 soon (as soon as it goes EOL end of November). I can already see tools dropping support for it.

Existing 7.2 phpqa images will still be available, it's just that they won't be updated.

Unless someone starts helping me with maintenance, my approach needs to remain on the "best effort" basis.

**Pull request closed without merging**
