### PR TITLE
Switch to Composer 2

### PR DESCRIPTION
**Pull request by jakzal**

### CODE REVIEW

**Comment by dkarlovi** [comment]
Note: I believe there would be some value to keep Composer 1 in the image for some time still, even as `composer1`. It's likely the transition period will be required until the plugins stabilize.

**Comment by jakzal** [comment]
@dkarlovi thinking about it more, as a workaround for potential issues, people can always downgrade themselves.

**Comment by dkarlovi** [comment]
@jakzal makes sense. :+1:

**Comment by dkarlovi** [comment]
Seems to work? Nice!

**Pull request merged**
