### PR TITLE
Add nomaduro/phpinsights

### LINKED ISSUE #102: Add nunomaduro/phpinsights
Link: https://github.com/nunomaduro/phpinsights

It was released a few hours ago, I just discovered it and it seems really promising, so to ensure easier testing and integration, I think it could be integrated to this phpqa tool 😄

### PR DESCRIPTION
**Pull request by Pierstoval**
I could not really succeed in testing this, but I guess the format should be right 😄 

What I know is that it created the right symlink, and when I executed the binary manually, it worked 👍 

Fixes #102

### CODE REVIEW

**Comment by jakzal** [comment]
It doesn't support php 7.1, so the build is failing: https://travis-ci.com/jakzal/toolbox/jobs/202783687#L666

**Comment by jakzal** [comment]
To fix the build please exclude the phpinsights on php 7.1 by tagging it as follows:

```
{
    ...,
    "tags": ["exclude-php:7.1"]
}
```

**Comment by Pierstoval** [comment]
Just pushed the change 😄

**Comment by jakzal** [comment]
Thank you @Pierstoval 🍺

**Pull request merged**
