### PR TITLE
Add twigcs

### PR DESCRIPTION
**Pull request by hussainweb**
Add the twigcs command from https://github.com/friendsoftwig/twigcs

### CODE REVIEW

**Comment by jakzal** [comment]
I noticed there's a phar published on github releases, can we use it instead of composer? i.e. https://github.com/friendsoftwig/twigcs/releases/download/v3.2.2/twigcs.phar

**Comment by hussainweb** [comment]
Thanks for finding this. I didn't check the releases page and it wasn't in the README.

One question: How do I make it able to download a version selectively (or maybe the latest version)? Or should I just hardcode the latest release and create a new PR for an update?

**Comment by jakzal** [comment]
Use the latest stable version. I've got a daily job running that discovers new versions and sends a pull request automatically.

**Comment by hussainweb** [comment]
@jakzal, I just pushed a change using 3.22 which is the latest stable. Will you code also be able to pick up major version updates? There is a 4.0 right now but only in beta.

**Comment by jakzal** [comment]
Thank you @hussainweb :)

**Comment by jakzal** [comment]
> Will your daily job also be able to pick up major version updates? There is a 4.0 right now but only in beta.

Currently, it won't. I guess I'll have to start filtering betas out. There's a need for this for another project too.

**Comment by jakzal** [comment]
Actually, BETA releases are marked as pre-releases. We're good 👍

**Pull request merged**
