### PR TITLE
update deptrac to version 0.7.1

### PR DESCRIPTION
**Pull request by smoench**

### CODE REVIEW

**Comment by jakzal** [comment]
Thank you! 🍺 

By the way, these updates happen automatically. No need to worry about it :)

**Comment by githoober** [comment]
@jakzal how often do then happen? I was gonna update the tools to version 0.8.0 of deptrac since it's still on the older one 0.7.1.

**Comment by jakzal** [comment]
@githoober daily. Deptrac 0.8.0 is in: https://github.com/jakzal/toolbox/blob/master/resources/tools.json#L97

Did you pull the latest docker image?

**Comment by jakzal** [comment]
@githoober I just made new releases of toolbox and phpqa. Once docker images build (might take a while), deptrac 0.8.0 will be included in the latest release. Not sure how I missed it earlier.

**Comment by githoober** [comment]
@jakzal thanks. Deptrack just released 0.8.1. Will the tools update to it properly?

**Pull request merged**
