### PR TITLE
Enable PHP-CS-Fixer on PHP 8

### PR DESCRIPTION
**Pull request by hason**
Composer install on PHP8 is now possible with the release of 2.17

### CODE REVIEW

**Comment by jakzal** [comment]
Looks like the phar wasn't updated yet.

**Comment by hason** [comment]
@jakzal Fixed

**Comment by jakzal** [comment]
Thank you @hason 🍺

**Comment by jakzal** [comment]
@hason php-cs-fixer's failing on PHP 8 again. Do you know what's that about? https://github.com/jakzal/toolbox/pull/335/checks?check_run_id=1774219103#step:4:248

**Comment by hason** [comment]
@jakzal 8.0.0 is not supported, 8.0.1+ is supported by php-cs-fixer

**Pull request merged**
